name: deploy_updated_code_on_hrmos_server.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image for amd64
        run: |
          docker buildx create --use || true
          docker buildx build \
            --platform linux/amd64 \
            -t 423623854229.dkr.ecr.ap-northeast-1.amazonaws.com/hrmos_scraper:latest \
            --push .

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_SSH_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Stop and remove running container if exists
            if [ $(docker ps -q -f name=hrmos_scraper) ]; then
              docker stop hrmos_scraper
              docker rm hrmos_scraper
            fi

            # Remove all docker images (optional)
            docker rmi -f $(docker images -q) || true

            # Login to ECR from EC2
            aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 423623854229.dkr.ecr.ap-northeast-1.amazonaws.com

            # Pull latest image
            docker pull 423623854229.dkr.ecr.ap-northeast-1.amazonaws.com/hrmos_scraper:latest

            # Run container
            docker run -d -p 3000:3000 -e AWS_REGION=ap-northeast-1 --name hrmos_scraper 423623854229.dkr.ecr.ap-northeast-1.amazonaws.com/hrmos_scraper:latest
